### ISSUE TITLE
I want to use .obj file from my remote storage instead of local?

### ISSUE THREAD

**Issue by KhoaNPA** [iosdevzone/GettingStartedWithModelIO#3]
```
let url = URL.init(string: "https://s3.amazonaws.com/3dimagetest/Fighter.obj")
let asset = MDLAsset(url:url!)
guard let object = asset.object(at: 0) as? MDLMesh else {
      fatalError("Failed to get mesh from asset.")
}
```

I meet error 

> "Failed to get mesh from asset."

 and

>  "Could not open OBJ file"

Notes: I made the link public, free to access.

**Comment by iosdevzone** [comment]
I'm pretty sure it has to be a file URL (although looking at the Apple documentation I did not see that mentioned!) Try downloading the file and using a URL to the local file.

**Comment by meshula** [comment]
ModelIO will only fetch from URLs starting with file:/// The NSURL interface is meant to be handy when using things like bundles.

**Comment by iosdevzone** [comment]
@meshula I thought I remembered reading that somewhere, but could not find it anywhere in the Apple docs for `MDLAsset.init`, any ideas where they specify that? Would be nice to add a link to it in this issue.

**Comment by khoanpase61742** [comment]
@meshula  I tried to download my file to local, then getting its path with format file:///... But there's still same error above, it fails to convert MDLAsset to MDLMesh.

**Comment by KhoaNPA** [comment]
I fixed my issue. My issue is that I converted the file before the downloading is finished. Therefore, the local path is created but data is empty because download process hasn't finished yet. 

> I use async to finish downloading first then converting it.

**Comment by meshula** [comment]
@iosdevzone I think I might have mentioned the requirement of using file:/// URLs during one of my Model I/O presentations at WWDC.

The most relevant documentation you are going to find is this:

https://developer.apple.com/documentation/foundation/nsdata/1407864-initwithcontentsofurl

Certain file import types such as USD and OBJ contain embedded file system file references, and these do not redirect through NSURL. So although NSURL might work for non file URLs in certain cases, in practice there are many caveats. Nonetheless, I'd recommend filing a Radar requesting documentation of the limitations.

@khoanpase61742 Glad you found a solution :)

**Comment by iosdevzone** [comment]
@meshula Thanks for tracking that down and providing more info. Will radar as soon as I get a moment. (BTW some of my Model I/O radars have been open for more than a year now e.g. 32492783, 26531102, 26190262; bit of a disincentive to take the time to file when it seems I am "wasting my sweetness on the desert air" -- if you could take a peek it would be great!)
